### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by Riseryn** [kalliope-project/kalliope_neuron_gmail#5]
Hello
with kalliope 0.6.0 i have the following error

 ```
File "/usr/local/lib/python3.7/dist-packages/gmail/__init__.py", line 16, in <module>
    from .gmail import Gmail
  File "/usr/local/lib/python3.7/dist-packages/gmail/gmail.py", line 3, in <module>
    from exceptions import *
ModuleNotFoundError: No module named 'exceptions'
```

**Comment by Sispheor** [comment]
This neuron is based on [a lib gmai](https://pypi.org/project/pygmail/)l which is totally deprecated and not python 3 compliant.
It would need to be rewritten entirely.
I think I'll delete it.

**Comment by tom333** [comment]
Hi 
I've made an update here : https://github.com/tom333/kalliope_neuron_gmail/tree/feature/simplegmail
Does it worth a pull request ?

**Comment by Sispheor** [comment]
Sure go ahead.
